# Generated by Django 3.1.2 on 2020-10-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('fundReason', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
