# Generated by Django 3.1.2 on 2020-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startfund',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='images'),
        ),
    ]
