# Generated by Django 3.1.2 on 2020-10-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_auto_20201024_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startfund',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
